name: Channels

on:
  workflow_dispatch:
    inputs:
      conda-version:
        description: 'Conda Version'
        required: true
        default: '23.1.0'
        type: choice
        options:
        - 'main'
        - '23.1.0'
        - '22.11.1'
        - '22.11.0'
        - '22.9.0'
      conda-libmamba-version:
        description: 'conda-libmamba-solver Version'
        required: true
        default: '23.1.0'
        type: choice
        options:
        - 'main'
        - '23.1.0'
        - '22.12.0'
        - '22.11.0'
      mamba-version:
        description: 'Mamba Version'
        required: true
        default: '1.3.1'
        type: choice
        options:
        - '1.3.1'
      os:
        description: 'Operating System'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - macos-latest
          - ubuntu-latest
          - windows-latest

jobs:
  conda-libmamba-solver:
    name: conda-libmamba-solver=${{ inputs.conda-libmamba-version }} os=${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@master

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
          conda-version: ${{ inputs.conda-version }}

      - name: Installation
        shell: bash -el {0}
        run: conda install -c conda-forge conda-libmamba-solver==${{ inputs.conda-libmamba-version }}

      - name: Conda Info
        shell: bash -el {0}
        run: |
          printf '{"channels": ["${{ inputs.channel }}"], "solver": "libmamba"}' > ~/.condarc
          conda info
          conda config --show
          conda list

      - name: Setup tmate session
        shell: bash -el {0}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
        with:
          limit-access-to-actor: true
