name: Reproducibility

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        conda-version: ["22.11.1", "22.11.0"]
        conda-libmamba-version: ["22.12.0"]
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@master

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""

      - name: Installation
        shell: bash -el {0}
        run: conda install -c conda-forge conda==${{ matrix.conda-version }} conda-libmamba-solver==${{ matrix.conda-libmamba-version }}

      - name: Conda info
        shell: bash -el {0}
        run: |
          conda info
          conda list

      - name: Test
        shell: bash -el {0}
        run: python test_script.py
