name: Reproducibility

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        conda-version: ["23.1.0"]
        conda-libmamba-version: ["23.1.0"]
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@master

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""

      - name: Installation
        shell: bash -el {0}
        run: conda install -c conda-forge conda==${{ matrix.conda-version }} conda-libmamba-solver==${{ matrix.conda-libmamba-version }}

      - name: Conda info
        shell: bash -el {0}
        run: |
          conda info
          conda list

      - name: Test
        shell: bash -el {0}
        run: python tests/script.py

      - name: Checkout repositories
        if: matrix.os == 'ubuntu-latest'
        run: |
          git clone https://github.com/conda/conda
          git -C conda checkout "${{ matrix.conda-version }}"
          git clone https://github.com/conda/conda-libmamba-solver
          git -C conda-libmamba-solver checkout "${{ matrix.conda-libmamba-version }}"

      - name: Run tests
        if: matrix.os == 'ubuntu-latest'
        run: |
          docker run --rm \
            --platform=linux/amd64 \
            -v $PWD/conda:/opt/conda-src \
            -v $PWD/conda-libmamba-solver:/opt/conda-libmamba-solver-src \
            -v $PWD/tests:/opt/tests \
            ghcr.io/conda/conda-ci:main-linux-python3.9 \
            bash -c "source /opt/conda-libmamba-solver-src/dev/bashrc_linux.sh && python /opt/tests/script.py"
